In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
iris = pd.read_csv("iris_xlsx.csv")

In [4]:
iris_train, iris_test = train_test_split(iris, train_size = 0.7, # 70%
                                         random_state = 123)
print(len(iris))
print(len(iris_train))
print(len(iris_test))

150
105
45


In [5]:
iris_train.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width     Species
114           5.8          2.8           5.1          2.4   virginica
136           6.3          3.4           5.6          2.4   virginica
53            5.5          2.3           4.0          1.3  versicolor
19            5.1          3.8           1.5          0.3      setosa
38            4.4          3.0           1.3          0.2      setosa

In [7]:
import os
os.getcwd() # get current working directory

'C:\\Users\\Encaion\\Desktop\\KB_Asso'

In [ ]:
os.chdir() # change working directory

In [10]:
bank = pd.read_csv("C:/Users/Encaion/Desktop/KB_Asso/bank.csv", # 절대경로
                   sep = ";")
bank.head(2)

age         job  marital  education default  balance housing loan  \
0   30  unemployed  married    primary      no     1787      no   no   
1   33    services  married  secondary      no     4789     yes  yes   

    contact  day month  duration  campaign  pdays  previous poutcome   y  
0  cellular   19   oct        79         1     -1         0  unknown  no  
1  cellular   11   may       220         1    339         4  failure  no

In [11]:
iris.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [ ]:
iris.iloc[0, :4]

In [ ]:
iris.iloc[1, :4]

In [16]:
sum((iris.iloc[0, :4] - iris.iloc[1, :4]) ** 2) ** 0.5

0.5385164807134502

In [17]:
iris_t = iris.iloc[:2, :4].transpose()
iris_t

0    1
Sepal.Length  5.1  4.9
Sepal.Width   3.5  3.0
Petal.Length  1.4  1.4
Petal.Width   0.2  0.2

In [19]:
iris_t["diff_sq"] = (iris_t[0] - iris_t[1]) ** 2

In [20]:
iris_t["diff_sq"].sum() ** 0.5

0.5385164807134502

In [21]:
from sklearn.preprocessing import MinMaxScaler # min-max
from sklearn.preprocessing import StandardScaler # standardization

* fit(): 주어진 데이터를 기반으로 규칙 학습
* transform(): fit() 으로 학습한 정보 기반 데이터 변환
* fit_transform(): 학습과 동시에 변환(1회성으로 사용)

In [22]:
iris.head(1)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa

In [ ]:
nor_minmax = MinMaxScaler().fit_transform(X = iris.iloc[:, :4])
nor_minmax[:4, ] # numpy array

In [26]:
df_nor_minmax = pd.DataFrame(nor_minmax,
                             columns = iris.columns[:4])
df_nor_minmax.head(2)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0      0.222222     0.625000      0.067797     0.041667
1      0.166667     0.416667      0.067797     0.041667

In [27]:
df_nor_minmax.agg(["min", "max"])

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
min           0.0          0.0           0.0          0.0
max           1.0          1.0           1.0          1.0

In [28]:
from sklearn.metrics import mean_squared_error # MSE
from sklearn.metrics import mean_absolute_error # MAE

In [31]:
mean_squared_error(y_true = [1], y_pred = [5]) ** 0.5 # RMSE

4.0

In [32]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score

In [33]:
from statsmodels.formula.api import ols

In [34]:
df = pd.read_csv("linear_regression_01.csv")
model = ols("y ~ x", data = df).fit() # 종속변수 ~ 독립변수
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.129
Model:                            OLS   Adj. R-squared:                  0.089
Method:                 Least Squares   F-statistic:                     3.257
Date:                Fri, 30 Apr 2021   Prob (F-statistic):             0.0848
Time:                        11:27:22   Log-Likelihood:                -53.868
No. Observations:                  24   AIC:                             111.7
Df Residuals:                      22   BIC:                             114.1
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      0.9909      0.908      1.091      0.287      -0.893       2.875
x              0.3732      0.207      1.805      0.085      -0.056       0.802
==============================================================================
Omnibus:                        3.957   Durbin-Watson:                   0.999
Prob(Omnibus):                  0.138   Jarque-Bera (JB):                1.902
Skew:                           0.380   Prob(JB):                        0.386
Kurtosis:                       1.849   Cond. No.                         8.50
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

$y = 0.3732x + 0.9909$ --> $y = 0.9909$

In [35]:
iris.head(1)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa

In [37]:
# model = ols("Petal.Length ~ Petal.Width", data = iris).fit() # 변수명에 마침표 xxx

In [39]:
iris = iris.rename(columns = {"Petal.Length": "PL", "Petal.Width": "PW"})
model = ols("PL ~ PW", data = iris).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                     PL   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.927
Method:                 Least Squares   F-statistic:                     1882.
Date:                Fri, 30 Apr 2021   Prob (F-statistic):           4.68e-86
Time:                        11:41:36   Log-Likelihood:                -101.18
No. Observations:                 150   AIC:                             206.4
Df Residuals:                     148   BIC:                             212.4
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      1.0836      0.073     14.850      0.000       0.939       1.228
PW             2.2299      0.051     43.387      0.000       2.128       2.332
==============================================================================
Omnibus:                        2.438   Durbin-Watson:                   1.430
Prob(Omnibus):                  0.295   Jarque-Bera (JB):                1.966
Skew:                           0.211   Prob(JB):                        0.374
Kurtosis:                       3.369   Cond. No.                         3.70
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [ ]:
bike = pd.read_csv("bike.csv")
bike.head(1)

In [42]:
model = ols("registered ~ holiday + temp + humidity + windspeed", bike).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             registered   R-squared:                       0.162
Model:                            OLS   Adj. R-squared:                  0.162
Method:                 Least Squares   F-statistic:                     527.6
Date:                Fri, 30 Apr 2021   Prob (F-statistic):               0.00
Time:                        13:07:19   Log-Likelihood:                -69102.
No. Observations:               10886   AIC:                         1.382e+05
Df Residuals:                   10881   BIC:                         1.383e+05
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept    148.4446      6.936     21.403      0.000     134.849     162.040
holiday      -18.8170      7.954     -2.366      0.018     -34.409      -3.225
temp           5.8815      0.171     34.481      0.000       5.547       6.216
humidity      -1.8773      0.073    -25.771      0.000      -2.020      -1.735
windspeed      0.3780      0.171      2.205      0.027       0.042       0.714
==============================================================================
Omnibus:                     3345.379   Durbin-Watson:                   0.479
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             9703.931
Skew:                           1.620   Prob(JB):                         0.00
Kurtosis:                       6.301   Cond. No.                         413.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [43]:
from statsmodels.formula.api import ols
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
df = pd.read_csv("bike.csv")
df_train, df_test = train_test_split(df, train_size = 0.7, random_state = 123)
model = ols("registered ~ workingday + atemp + humidity + windspeed",
            data = df_train).fit()
print(model.rsquared) # 결정계수
print(model.params) # 계수

In [ ]:
pred = model.predict(df_test[["workingday", "atemp", "humidity", "windspeed"]])
pred[:3]

In [55]:
mean_squared_error(y_true = df_test["registered"], y_pred = pred) ** 0.5 # RMSE

136.78698905996671

In [56]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
df = pd.read_csv("bike.csv")
df_train, df_test = train_test_split(df, train_size = 0.7, random_state = 123)
X_cols = ["workingday", "atemp", "humidity", "windspeed"]
model = LinearRegression().fit(X = df_train[X_cols],
                               y = df_train["registered"])
print(model.intercept_) # 절편
print(model.coef_) # 계수

In [ ]:
pd.Series(model.coef_, index = X_cols)

In [ ]:
pred = model.predict(df_test[X_cols])
pred[:3]

In [70]:
mean_squared_error(y_true = df_test["registered"], y_pred = pred) ** 0.5

136.78698905996671

업무일이 아니고, 체감온도가 20도, 상대습도가 50%, 풍속이 3인 경우 정기권 이용자(registered)의 자전거 대여수를 확인하시오. <br>
※ 단, 결과값은 반올림하여 정수로 표기한다.

In [73]:
df_test2 = pd.DataFrame([[0, 20, 50, 3]],
                        columns = X_cols)
df_test2

workingday  atemp  humidity  windspeed
0           0     20        50          3

In [80]:
model.predict(df_test2)[0]

127.21668064942182

In [79]:
round(model.predict(df_test2)[0])

127.0

In [84]:
from statsmodels.formula.api import ols
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [86]:
df = pd.read_csv("diamonds.csv")
df = pd.get_dummies(df, columns = ["cut"],
                    drop_first = True)
df.head(1)

carat color clarity  depth  table  price     x     y     z  cut_Good  \
0   0.23     E     SI2   61.5   55.0    326  3.95  3.98  2.43         0   

   cut_Ideal  cut_Premium  cut_Very Good  
0          1            0              0

In [90]:
df = df.rename(columns = {"cut_Very Good": "cut_VeryGood"})

In [91]:
df_train, df_test = train_test_split(df, train_size = 0.7, random_state = 123)
formula = "price ~ carat + " + " + ".join(df_train.columns[9:])
model = ols(formula,
            data = df_train).fit()
print(model.rsquared) # 결정계수
print(model.params) # 계수

0.8562085935073284
Intercept      -3874.917304
carat           7878.466778
cut_Good        1118.019989
cut_Ideal       1793.349436
cut_Premium     1434.414493
cut_VeryGood    1491.598754
dtype: float64


In [95]:
from statsmodels.api import Logit
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [108]:
df = pd.read_csv("logistic_regression_01.csv")
df.head(2)

admit  gre   gpa  rank
0      0  380  3.61     3
1      1  660  3.67     3

In [ ]:
df_train, df_test = train_test_split(df, train_size = 0.8, random_state = 123)
model = Logit(endog = df_train["admit"], # 종속변수
              exog = df_train[["gre", "gpa", "rank"]]).fit()
# model.summary()

In [109]:
model.params # 회귀계수

import numpy as np
np.exp(model.params) # OR, Odds Ratio(승산비)

gre     1.000854
gpa     1.032646
rank    0.564301
dtype: float64

In [114]:
pred = model.predict(df_test[["gre", "gpa", "rank"]])
print(pred[:3])
pred_class = (pred > 0.5) + 0 # 경계값(문턱값)이 0.5인 경우

234    0.555876
42     0.370345
303    0.392754
dtype: float64


In [102]:
accuracy_score(y_true = df_test["admit"], y_pred = pred_class)

0.7125

In [106]:
from sklearn.metrics import roc_auc_score

In [107]:
roc_auc_score(df_test["admit"], pred) # AUC

0.779532967032967

In [115]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [130]:
df = pd.read_csv("diabetes.csv")
df.head(1)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1

In [131]:
df_train, df_test = train_test_split(df, train_size = 0.7, random_state = 123)
X_cols = df_train.columns[:5]
model = LogisticRegression(random_state = 123).fit(X = df_train[X_cols],
                                                   y = df_train["Outcome"])

In [132]:
model.coef_
import numpy as np
np.exp(model.coef_).round(3)

array([[1.122, 1.038, 0.995, 1.018, 0.998]])

In [133]:
pred = model.predict_proba(df_test[X_cols])
pred[:4, ] # 두 번째 column의 값이 종속변수가 1이될 확률

array([[0.1842226 , 0.8157774 ],
       [0.73663333, 0.26336667],
       [0.41006958, 0.58993042],
       [0.90931457, 0.09068543]])

In [134]:
pred_class = (pred[:, 1] > 0.5) + 0
pred_class[:3]

array([1, 0, 1])

In [135]:
accuracy_score(y_true = df_test["Outcome"], y_pred = pred_class)

0.7489177489177489

In [136]:
from sklearn.metrics import roc_auc_score
roc_auc_score(df_test["Outcome"], pred[:, 1]) # AUC

0.8537825810553082

In [129]:
roc_auc_score(df_test["Outcome"], pred_class) # 틀린 예시!!!!

0.6988636363636364

In [137]:
from sklearn.tree import DecisionTreeClassifier # 분류나무
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [149]:
df = pd.read_csv("bank.csv", sep = ";")
df.head(1)

age         job  marital education default  balance housing loan   contact  \
0   30  unemployed  married   primary      no     1787      no   no  cellular   

   day month  duration  campaign  pdays  previous poutcome   y  
0   19   oct        79         1     -1         0  unknown  no

In [150]:
df["y"] = (df["y"] == "yes") + 0
df["y"].unique()

array([0, 1])

In [ ]:
df_train, df_test = train_test_split(df, train_size = 0.7, random_state = 123)
X_cols = ["age", "balance", "duration", "campaign"]
model = DecisionTreeClassifier(random_state = 123).fit(X = df_train[X_cols],
                                                       y = df_train["y"])
model

In [155]:
pred = model.predict(df_test[X_cols])
pred

array([0, 1, 0, ..., 0, 0, 0])

In [156]:
accuracy_score(y_true = df_test["y"], y_pred = pred)

0.8422991893883567

In [163]:
from sklearn.tree import DecisionTreeRegressor # 회귀나무
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

In [ ]:
df = pd.read_csv("diabetes.csv")
df.head(1)

In [161]:
df_train, df_test = train_test_split(df, train_size = 0.8, random_state = 123)
X_cols = df.columns[:5]
model = DecisionTreeRegressor(random_state = 123).fit(X = df_train[X_cols],
                                                      y = df_train["BMI"])

In [162]:
pred = model.predict(df_test[X_cols])
pred[:3]

array([32. , 32.9, 27.1])

In [164]:
mean_squared_error(y_true = df_test["BMI"], y_pred = pred) ** 0.5

10.271148597235536

In [165]:
ser = pd.Series(["BC-A", "BC-B", "GC-K"])
ser

0    BC-A
1    BC-B
2    GC-K
dtype: object

In [ ]:
ser.str.split(pat = "-")

In [167]:
ser.str.split(pat = "-", expand = True)

0  1
0  BC  A
1  BC  B
2  GC  K

In [168]:
ser.str.replace(pat = "A", repl = "") # A를 없앨 수 있음

0    BC-@
1    BC-B
2    GC-K
dtype: object