In [ ]:
1 + 1

## 파이썬 시작하기

* 코드 입력
 - 연산자 좌우로 띄어쓰기 권장

<b style="color:#FF0000">Python!!!</b> 1일차!!!

In [ ]:
# 기본 코드 실습

In [ ]:
1 + 1 # 더하기

In [ ]:
# 주석(comment)

In [ ]:
for n in range(3):
    print(n)

In [ ]:
for n in range(3):
print(n)

In [ ]:
a = "\"Python\" is awesome. \n\tHello Python?"
print(a)

In [ ]:
a

In [ ]:
'abc'
"abc"

In [ ]:
'gggggggg'
"abc"

In [ ]:
print("kkk")
print("yyy")

In [ ]:
# 'It's mine'

In [ ]:
'It\'s mine'

In [ ]:
tx = "Hello!"

In [ ]:
tx[4]

In [ ]:
tx[0:4] # 0부터 시작하여 4 직전까지의 인덱스에 해당하는 tx 객체의 원소를 출력

## Q. tx객체의 원소를 출력하고자 한다. 첫 원소부터 뒤에서 두 번째 원소까지 출력하기 위한 코드는?

In [ ]:
tx[0:-1]

In [ ]:
print(tx[0:-1])

In [ ]:
tx[:-1]

# 05. 연산자

In [ ]:
5 // 2 # 몫

In [ ]:
5 % 2 # 나머지

In [ ]:
5 ** 2 # 지수 연산

In [ ]:
"파이썬" + "살려줘" # 문자의 경우 + 연산자로 이어붙일 수 있음

In [ ]:
(1 - 0.1) * (1 - 0.1)

In [ ]:
(1 - 0.1) ** 2

In [ ]:
(1 - 0.1) ** 10

In [ ]:
(1 + 0.01) ** 365

In [ ]:
"감자" == "고구마" # 같냐? --> 아니 ㅋㅋ

In [ ]:
"감자" != "고구마" # not equal, 좌우 원소가 서로 같지 않은지(다른지) 검사

In [ ]:
aa = [1, 2, 3]
bb = [4, 5, 6]

In [ ]:
aa + bb

In [ ]:
[5, 7, 9]

In [ ]:
import numpy as np
arr_aa = np.array([1, 2, 3])
arr_bb = np.array([4, 5, 6])
arr_aa + arr_bb

In [ ]:
bb = [2, 3, 4]
bb[2]

In [ ]:
bb[2] = [99, 99]
bb

In [ ]:
cc = [3, 4, 5]
cc[1:2] = [99, 99]
cc

In [ ]:
dd = [4, 5, 6]
dd[2:2] = [99, 99]
dd

In [ ]:
kk = [1, 2, 3]
del kk[0]

In [ ]:
kk

In [ ]:
ww = [2, 5, 3]
ww

In [ ]:
ww.sort()
ww

In [ ]:
ww.sort(reverse = True)
ww

In [ ]:
mm = [1, 2, 3]
mm

In [ ]:
mm.index(3)

In [ ]:
mm.index(5)

In [ ]:
uu = ["a", "b", "c"]
uu

In [ ]:
uu.index("b")

In [ ]:
tt = [1, 2, 3, 2]

In [ ]:
tt.count(3)

In [ ]:
dic = {"k1": 1,
       "k2": "aa", 
       "k3": [1, 2, 3]}
dic

In [ ]:
dic["new"] = [1, 2, 3]
dic

In [ ]:
num = "010-1234-5678"

In [ ]:
num.split("-")

In [ ]:
"-".join(["010", "1234", "5678"])

In [ ]:
"y ~ " + " + ".join(["x1", "x2", "x3"])

In [ ]:
score = 85

In [ ]:
if score >= 80:
    print("A")

In [ ]:
score >= 80

In [ ]:
for n in range(3):
    print(n)

In [ ]:
range(6) # 0부터 1씩 증가하는 정수가 6개

In [ ]:
for n in [0, 1, 2]:
    print(n)

In [ ]:
for n in range(10):
    print(n)

In [ ]:
listt = ["a", "b", "c"]
for i in listt:
    print(i)

In [ ]:
a = [2, 6, 7, 8, 9]
[num for num in a if num % 2 == 0]

In [ ]:
a = [2, 6, 7, 8, 9]
vec = [num for num in a if num % 2 == 0]
vec

In [ ]:
a = [2, 6, 7, 8, 9]
vec = []
for num in a:
    if num % 2 == 0:
        vec = vec + [num]
vec

In [ ]:
a = [2, 6, 7, 8, 9]
vec = []
for num in a:
    if num % 2 == 0:
        vec = vec + [num]
vec

In [ ]:
def udf_01(a):
    print(a)

In [ ]:
# udf_01()

In [ ]:
udf_01("Hello?")

In [ ]:
udf_01(a = "Hello?")

In [ ]:
len([2, 4, 6])

In [ ]:
len([2, 4, 6, 8]) # length의 len을 함수명으로 함.
# 입력되는 객체의 원소의 개수(즉, 객체의 길이)

## Q. 중첩되지 않은 숫자를 원소로 가지는 비어있지 않은 리스트 객체를 입력으로 하고 출력은 평균값으로 하는 사용자 정의 함수 udf_mean() 을 만드시오.

입력 예시: \[4, 6, 8\] <br>
출력 예시: 6 또는 \[6\]

In [ ]:
temp = [4, 8, 12, 16]
def udf_mean(numList):
    sum = 0
    for i in numList:
        sum += i
    print(sum/len(numList))
udf_mean(temp)

In [ ]:
a = [4, 6, 13]
def udf_mean(arr):
    num = 0
    for item in arr:
        num = num + item
    return num/len(arr)

udf_mean(a)

In [ ]:
a = [4, 6, 8]
def udf_mean(x):
    return sum(x)/len(x)

In [ ]:
udf_mean([1, 4, 6, 8, 9])

In [2]:
import numpy as np

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [ ]:
np.array([[1, 2], [3, 4]])

In [ ]:
np.array([[1, 2], 
          [3, 4]])

In [ ]:
np.zeros((5, 4))

In [18]:
np.random.seed(456) # 난수 생성을 고정
# 평균과 표준편차가 2인 정규분포를 따르는 임의의 숫자 100개 추출
np_rnorm = np.random.normal(loc = 2, 
                            scale = 2,
                            size = 100)
print(np_rnorm.mean())
print(np_rnorm.std())

2.2894590675755655
1.8408877860982824


In [32]:
np.random.seed(999)

In [35]:
np_rnorm = np.random.normal(loc = 2, 
                            scale = 2,
                            size = 100)
print(np_rnorm.mean())
print(np_rnorm.std())

1.561604984831296
1.9261906247364986


In [37]:
vec = np.array([2, 4, 6, 8])
np.where(vec >= 5, 1, 0)

array([0, 0, 1, 1])

엑셀의 if() 함수와 동작이 같음. 각 원소마다 조건검사를 하여 True이면 두 번째 값이, False이면 세 번째 인자의 값이 할당됨

In [39]:
import pandas as pd

In [40]:
ser = pd.Series([2, 4, 8, 9, 15])
ser

0     2
1     4
2     8
3     9
4    15
dtype: int64

In [41]:
ser.idxmax() # idx --> index

4

In [42]:
ser.idxmin()

0

In [43]:
ser

0     2
1     4
2     8
3     9
4    15
dtype: int64

In [46]:
ser == 2

0     True
1    False
2    False
3    False
4    False
dtype: bool

In [45]:
ser[ser == 2]

0    2
dtype: int64

In [48]:
ser > 4

0    False
1    False
2     True
3     True
4     True
dtype: bool

In [47]:
ser[ser > 4]

2     8
3     9
4    15
dtype: int64

In [49]:
ser[(ser >= 4) & (ser <= 9)] # 4 이상 이면서(&) 9 이하인 원소

1    4
2    8
3    9
dtype: int64

In [52]:
ser[(ser == 4) | (ser == 9)]

1    4
3    9
dtype: int64

In [50]:
ser.isin([4, 9])

0    False
1     True
2    False
3     True
4    False
dtype: bool

In [51]:
ser[ser.isin([4, 9])] # 4 또는 9

1    4
3    9
dtype: int64

In [53]:
df = pd.DataFrame({"aa": [1, 2, 3],
                   "bb": ["a", "b", "c"]})
df

aa bb
0   1  a
1   2  b
2   3  c

In [54]:
np.arange(6)

array([0, 1, 2, 3, 4, 5])

In [55]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [56]:
np.arange(4, 12, 2) # 4 이상 12 미만, 2씩 증가

array([ 4,  6,  8, 10])

In [57]:
np.arange(6).reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
np.arange(6).reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
pd.DataFrame(np.arange(6).reshape(3, 2))

0  1
0  0  1
1  2  3
2  4  5

In [63]:
# df[1, 1]
df.iloc[[0, 2], ] 

aa bb
0   1  a
2   3  c

In [64]:
df.iloc[[0, 2], :] # : 은 범위 전체를 의미

aa bb
0   1  a
2   3  c

In [65]:
df.loc[df["aa"] == 2, ]

aa bb
1   2  b

In [66]:
df.loc[df["aa"] != 2, ] # [ row, col ]

aa bb
0   1  a
2   3  c

In [67]:
df.aa # 권장 X
df["aa"]
df.iloc[:, 0]
df.loc[:, "aa"]

0    1
1    2
2    3
Name: aa, dtype: int64

In [68]:
df.shape

(3, 2)

In [69]:
df.ndim

2

In [70]:
df2 = pd.DataFrame([[1, 2], [3, 4]],
                   columns = ["shape", "ndim"])
df2

shape  ndim
0      1     2
1      3     4

In [71]:
df2.shape

(2, 2)

In [72]:
df2["shape"]

0    1
1    3
Name: shape, dtype: int64

In [75]:
ser = pd.Series([2, 4, 6, 8])
ser.isin([4, 9])

0    False
1     True
2    False
3    False
dtype: bool

In [76]:
ser[(ser == 4) | (ser == 9)]

1    4
dtype: int64

In [78]:
import os
os.listdir()

['.ipynb_checkpoints',
 'AWS_sample.txt',
 'bank.csv',
 'bike.csv',
 'bike.json',
 'bike_rental.csv',
 'bike_weather.csv',
 'classification_data_01.csv',
 'class_210426.ipynb',
 'class_scores.csv',
 'dataset.zip',
 'diabetes.csv',
 'diamonds.csv',
 'elec_load.csv',
 'iris_missing.csv',
 'iris_xlsx.csv',
 'iris_xlsx.xlsx',
 'join_list.csv',
 'join_room.csv',
 'linear_regression_01.csv',
 'logistic_regression_01.csv',
 'rating_chocobar.csv',
 'traffic_accident.txt']

In [80]:
# local 환경(HDD, SSD 와 같은 보조기억장치)에서 파일을 pandas의 read_csv() 함수로 
# 읽어와서 복사한 내용을 df 객체에 저장
df = pd.read_csv("bike.csv")
# df.iloc[:3]
# df.iloc[:3, ]
df.head(3) # 첫 n개의 row를 출력하며 기본값은 5

datetime  season  holiday  workingday  weather  temp   atemp  \
0  2011-01-01 00:00:00       1        0           0        1  9.84  14.395   
1  2011-01-01 01:00:00       1        0           0        1  9.02  13.635   
2  2011-01-01 02:00:00       1        0           0        1  9.02  13.635   

   humidity  windspeed  casual  registered  count  
0        81        0.0       3          13     16  
1        80        0.0       8          32     40  
2        80        0.0       5          27     32

In [ ]:
df.tail() # 마지막 n개의 row를 출력하며 기본값은 5

In [81]:
df = pd.read_csv("AWS_sample.txt")
df.head(2)

AWS_ID#TM#TA#Wind#X.
0  108#2016-07-01 00#24.2#2.3#=
1  108#2016-07-01 01#24.3#2.3#=

In [82]:
df = pd.read_csv("AWS_sample.txt", sep = "#") # 값 구분은 #으로 되어있음
df.head(2)

AWS_ID             TM    TA  Wind X.
0     108  2016-07-01 00  24.2   2.3  =
1     108  2016-07-01 01  24.3   2.3  =

In [83]:
len(df)

5886

In [84]:
df.shape # row, column

(5886, 5)

### Q1. elec_load.csv 파일을 읽어와서 elec 객체에 저장하시오.

In [87]:
elec = pd.read_csv("elec_load.csv")

### Q2. elec 객체의 row 개수와 column 개수를 확인하시오.

In [88]:
elec.shape

(3546, 27)

### Q3. X1HR 변수의 평균값을 산출하시오.

In [89]:
elec["X1HR"].mean()

46606.40778341793

In [91]:
elec["X1HR"].sum() / len(elec)

46606.40778341793

### Q4. 2009년도 데이터를 추출하여 elec_2009 객체에 저장하고 데이터의 개수를 확인하시오.

In [92]:
elec_2009 = elec.loc[elec["YEAR"] == 2009, ]
len(elec_2009)

365

### Q5. 2010년 12월의 X10HR 변수의 평균값은 얼마인가?

In [93]:
elec.loc[(elec["YEAR"] == 2010) & (elec["MONTH"] == 12), "X10HR"].mean()

48852.48387096774

In [94]:
os.getcwd() # get current working directory

'C:\\Users\\Encaion\\Desktop\\KB_Asso'